
    - name: Install dnf-plugins-core
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present

    - name: Add Docker CE repository
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: '0644'
    - name: Install Docker Engine and plugins
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: true
        allowerasing: true

    - name: Enable and start Docker service
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started

    - name: Add '{{ ansible_user }}' to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Check version
      ansible.builtin.command: docker --version
      register: docker_version
      changed_when: false

    - name: Display version
      ansible.builtin.debug:
        msg: "Docker is ready: {{ docker_version.stdout }}"