
services:
  periphery:
    image: ghcr.io/moghtech/komodo-periphery:${KOMODO_VERSION:-2}
    init: true
    restart: unless-stopped
    environment:
      PERIPHERY_CORE_ADDRESS: ${KOMODO_CORE_ADDRESS}
      PERIPHERY_CONNECT_AS: ${KOMODO_SERVER_NAME}
      PERIPHERY_ONBOARDING_KEY: ${KOMODO_ONBOARDING_KEY}
      PERIPHERY_CORE_PUBLIC_KEYS: file:/config/keys/core.pub
      PERIPHERY_ROOT_DIRECTORY: ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}
      PERIPHERY_DISABLE_TERMINALS: false
      PERIPHERY_DISABLE_CONTAINER_EXEC: false
      PERIPHERY_INCLUDE_DISK_MOUNTS: /etc/hostname
    volumes:
      - keys:/config/keys
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}

volumes:
  keys: